/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keyboard_KeyboardApi */

#ifndef _Included_keyboard_KeyboardApi
#define _Included_keyboard_KeyboardApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     keyboard_KeyboardApi
 * Method:    testCommunication
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_keyboard_KeyboardApi_testCommunication
  (JNIEnv *, jobject, jstring);

/*
 * Class:     keyboard_KeyboardApi
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_keyboard_KeyboardApi_testString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     keyboard_KeyboardApi
 * Method:    testInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_keyboard_KeyboardApi_testInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     keyboard_KeyboardApi
 * Method:    initCpp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_keyboard_KeyboardApi_initCpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
